# Revenue Engine
# Autonomous revenue generation across multiple streams

param(
    [Parameter(Mandatory=$true)]
    [ValidateSet("check", "pod-update", "newsletter", "signals", "report")]
    $Command,
    
    [string]$ProductId,
    [switch]$Force
)

$RevenueDir = "C:\Users\quent\.openclaw\workspace\revenue"
$StreamsFile = "$RevenueDir\streams.json"
$DailyLog = "$RevenueDir\daily_log.json"

# Ensure directories exist
if (-not (Test-Path $RevenueDir)) { New-Item -ItemType Directory -Path $RevenueDir -Force | Out-Null }

# Initialize streams config if not exists
if (-not (Test-Path $StreamsFile)) {
    $streams = @{
        pod = @{
            name = "Print-on-Demand"
            status = "blocked"
            blocker = "Pricing fix needed"
            daily_revenue = 0
            potential = 150
            products = 5
            platform = "Etsy/Printify"
        }
        newsletter = @{
            name = "Investment Newsletter"
            status = "ready"
            blocker = $null
            daily_revenue = 0
            potential = 33
            subscribers = 0
            platform = "Email"
        }
        signals = @{
            name = "Trading Signals"
            status = "ready"
            blocker = $null
            daily_revenue = 0
            potential = 16
            subscribers = 0
            platform = "Telegram"
        }
        code = @{
            name = "Code Products"
            status = "ready"
            blocker = $null
            daily_revenue = 0
            potential = 10
            products = 0
            platform = "Gumroad/GitHub"
        }
    } | ConvertTo-Json -Depth 5
    $streams | Set-Content $StreamsFile
}

function Get-StreamsStatus {
    $streams = Get-Content $StreamsFile | ConvertFrom-Json
    Write-Host "═══════════════════════════════════════"
    Write-Host "  REVENUE STREAMS STATUS"
    Write-Host "═══════════════════════════════════════"
    
    $total = 0
    foreach ($key in $streams.PSObject.Properties.Name) {
        $s = $streams.$key
        $status = if ($s.status -eq "active") { "🟢" } elseif ($s.status -eq "ready") { "🟡" } else { "🔴" }
        Write-Host "$status $($s.name)"
        Write-Host "   Status: $($s.status)"
        if ($s.blocker) { Write-Host "   Blocker: $($s.blocker)" }
        Write-Host "   Daily: €$($s.daily_revenue) | Potential: €$($s.potential)"
        $total += $s.daily_revenue
    }
    
    Write-Host "═══════════════════════════════════════"
    Write-Host "  TOTAL DAILY: €$total"
    Write-Host "  TOTAL MONTHLY: €$($total * 30)"
    Write-Host "═══════════════════════════════════════"
}

function Update-PODStatus {
    Write-Host "═══════════════════════════════════════"
    Write-Host "  POD BUSINESS UPDATE"
    Write-Host "═══════════════════════════════════════"
    Write-Host ""
    Write-Host "ACTION REQUIRED (Manual):"
    Write-Host "1. Log into Printify dashboard"
    Write-Host "2. Go to Products"
    Write-Host "3. Edit prices: $4.91 → €22.99-29.99"
    Write-Host "4. Reconnect Etsy store"
    Write-Host "5. Delete duplicate 'DESIGN' products"
    Write-Host ""
    Write-Host "Once done, run: revenue.ps1 -Command check"
}

function Generate-Newsletter {
    Write-Host "═══════════════════════════════════════"
    Write-Host "  NEWSLETTER GENERATION"
    Write-Host "═══════════════════════════════════════"
    
    # Fetch latest market data
    $marketData = & "C:\Users\quent\.openclaw\workspace\mission_control\market_data_service.js" --json 2>$null | ConvertFrom-Json
    
    $newsletter = @"
# Daily Market Brief — $(Get-Date -Format 'yyyy-MM-dd')

## Market Snapshot
$(foreach ($asset in $marketData.assets.PSObject.Properties) {
    "- $($asset.Name): `$($asset.Value.price)` | $($asset.Value.change_24h)%"
})

## Key Insights
- Fear & Greed Index: Check alternative.me
- Top Mover: $(($marketData.assets.PSObject.Properties | Sort-Object { [decimal]$_.Value.change_24h } -Descending | Select-Object -First 1).Name)

## Action Items
- Review portfolio positions
- Check stop-losses
- Monitor pre-market for Monday

Generated by Claw AI Agent
"@
    
    $outputPath = "$RevenueDir\newsletter\draft_$(Get-Date -Format 'yyyyMMdd').md"
    if (-not (Test-Path "$RevenueDir\newsletter")) { New-Item -ItemType Directory -Path "$RevenueDir\newsletter" -Force | Out-Null }
    $newsletter | Set-Content $outputPath
    
    Write-Host "Newsletter draft saved to: $outputPath"
    Write-Host "Send via: SendGrid/Mailgun API"
}

function Generate-TradingSignals {
    Write-Host "═══════════════════════════════════════"
    Write-Host "  TRADING SIGNALS"
    Write-Host "═══════════════════════════════════════"
    
    # Simple signal logic
    $signals = @()
    
    # BTC signal
    $btc = Invoke-RestMethod -Uri "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd&include_24hr_change=true" -TimeoutSec 10
    if ($btc.bitcoin.usd_24h_change -lt -5) {
        $signals += "🟢 BTC OVERSOLD: $($btc.bitcoin.usd) | Change: $($btc.bitcoin.usd_24h_change)% | Consider DCA"
    }
    
    # MSTR signal
    $mstrData = & "C:\Users\quent\.openclaw\workspace\mission_control\market_data_service.js" --json 2>$null | ConvertFrom-Json
    if ($mstrData.assets.MSTR.change_24h -gt 5) {
        $signals += "🟢 MSTR BREAKOUT: +$($mstrData.assets.MSTR.change_24h)% | Momentum play"
    }
    
    Write-Host "Signals for today:"
    foreach ($signal in $signals) {
        Write-Host "  $signal"
    }
    
    if ($signals.Count -eq 0) {
        Write-Host "  ⚪ No strong signals today. Hold positions."
    }
}

function Generate-RevenueReport {
    $streams = Get-Content $StreamsFile | ConvertFrom-Json
    $total = 0
    foreach ($key in $streams.PSObject.Properties.Name) {
        $total += $streams.$key.daily_revenue
    }
    
    $report = @{
        date = Get-Date -Format "yyyy-MM-dd"
        total_daily = $total
        total_monthly = $total * 30
        streams = $streams
        actions = @(
            "Fix POD pricing (manual)",
            "Setup SendGrid for newsletter",
            "Create Telegram channel for signals",
            "Package code products for Gumroad"
        )
    } | ConvertTo-Json -Depth 5
    
    $report | Set-Content "$RevenueDir\report_$(Get-Date -Format 'yyyyMMdd').json"
    Write-Host "Report saved. Action items listed."
}

# ═══════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════

switch ($Command) {
    "check" { Get-StreamsStatus }
    "pod-update" { Update-PODStatus }
    "newsletter" { Generate-Newsletter }
    "signals" { Generate-TradingSignals }
    "report" { Generate-RevenueReport }
}

Write-Host ""
Write-Host "Revenue engine ready. Activate streams to start earning."