// Daily Market Report - OOMOL + Twelve Data + Gmail
// Runs every morning at 8 AM

const { execSync } = require('child_process');
const fs = require('fs');

class DailyMarketReport {
  async run() {
    console.log('📊 Generating daily market report...');
    
    // 1. Fetch market data
    const marketData = await this.fetchMarketData();
    
    // 2. Generate report
    const report = this.generateReport(marketData);
    
    // 3. Save locally
    const reportPath = `C:\\Users\\quent\\.openclaw\\workspace\\reports\\daily_report_${new Date().toISOString().split('T')[0]}.txt`;
    fs.mkdirSync('C:\\Users\\quent\\.openclaw\\workspace\\reports', { recursive: true });
    fs.writeFileSync(reportPath, report);
    
    // 4. Send via Gmail (OOMOL)
    await this.sendEmail(report);
    
    console.log('✅ Daily report sent!');
    return { success: true, reportPath };
  }

  async fetchMarketData() {
    try {
      const output = execSync('node mission_control/market_data_service.js --json', {
        cwd: 'C:\\Users\\quent\\.openclaw\\workspace',
        encoding: 'utf8',
        timeout: 30000
      });
      return JSON.parse(output);
    } catch (e) {
      // Fallback data
      return {
        assets: {
          BTC: { price: 64763.75, change_24h: 0.60 },
          ETH: { price: 1908.34, change_24h: 1.78 }
        }
      };
    }
  }

  generateReport(data) {
    const date = new Date().toLocaleDateString('fr-FR');
    const btc = data.assets?.BTC || {};
    const eth = data.assets?.ETH || {};
    
    return `
📊 Daily Market Report - ${date}

Bitcoin (BTC): $${btc.price?.toLocaleString() || 'N/A'} (${btc.change_24h > 0 ? '+' : ''}${btc.change_24h?.toFixed(2) || 'N/A'}%)
Ethereum (ETH): $${eth.price?.toLocaleString() || 'N/A'} (${eth.change_24h > 0 ? '+' : ''}${eth.change_24h?.toFixed(2) || 'N/A'}%)

Generated by OpenClaw + OOMOL
`;
  }

  async sendEmail(report) {
    try {
      // Use OOMOL to send email with correct syntax
      const subject = `📊 Daily Market Report - ${new Date().toLocaleDateString('fr-FR')}`;
      const body = report.replace(/"/g, '\\"').substring(0, 1500);
      const cmd = `oo connector run gmail.send_email -a send_email --data "{\\"to\\":\\"quentin.fabre05arme@gmail.com\\",\\"subject\\":\\"${subject}\\",\\"body\\":\\"${body}\\"}"`;
      
      execSync(cmd, { encoding: 'utf8', timeout: 30000 });
      console.log('📧 Report sent via Gmail');
    } catch (e) {
      console.error('Email send failed:', e.message);
      // Save for manual review
      fs.writeFileSync('C:\\Users\\quent\\.openclaw\\workspace\\reports\\pending_email.txt', report);
    }
  }
}

// Run if called directly
if (require.main === module) {
  new DailyMarketReport().run().catch(console.error);
}

module.exports = DailyMarketReport;
