#!/usr/bin/env node
/**
 * Generate markdown report from alternative data JSON
 */

const fs = require('fs');
const path = require('path');

const date = process.argv[2] || new Date().toISOString().split('T')[0];
const dataPath = path.join(__dirname, '..', 'data', 'alternative', `${date}.json`);

if (!fs.existsSync(dataPath)) {
  console.error('Data file not found:', dataPath);
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(dataPath, 'utf8'));

// Helper for severity emoji
function severityEmoji(sev) {
  return sev === 'HIGH' ? '🔴' : sev === 'MEDIUM' ? '🟡' : '🟢';
}

const report = `# Alpha Fund Alternative Data Report
**Date:** ${data.metadata.local_time}  
**UTC:** ${data.metadata.fetch_timestamp}  
**Cycle:** ${data.metadata.cycle_id}

---

## 📊 Market Snapshot
| Asset | Price | 24h Change | Signal |
|-------|-------|-----------|--------|
| BTC | $${data.market_snapshot.assets.BTC.price.toLocaleString()} | ${data.market_snapshot.assets.BTC.change_24h.toFixed(2)}% | ${data.market_snapshot.assets.BTC.signal} |
| ETH | $${data.market_snapshot.assets.ETH.price.toLocaleString()} | ${data.market_snapshot.assets.ETH.change_24h.toFixed(2)}% | ${data.market_snapshot.assets.ETH.signal} |
| MSTR | $${data.market_snapshot.assets.MSTR.price.toFixed(2)} | ${data.market_snapshot.assets.MSTR.change_24h.toFixed(2)}% | ${data.market_snapshot.assets.MSTR.signal} |
| HIMS | $${data.market_snapshot.assets.HIMS.price.toFixed(2)} | +${data.market_snapshot.assets.HIMS.change_24h.toFixed(2)}% | ${data.market_snapshot.assets.HIMS.signal} |

---

## 🧠 Sentiment Metrics
- **Fear & Greed:** ${data.sentiment.fear_greed.value} (${data.sentiment.fear_greed.classification}) — Trend: ${data.sentiment.fear_greed.trend}
- **Social Sentiment:** ${data.sentiment.social_sentiment.overall_sentiment} (sources: ${data.sentiment.social_sentiment.sources.length})

---

## ⛓️ On-Chain Metrics
- **Mempool Size:** ${data.on_chain.network_metrics.mempool_size.toLocaleString()} txs
- **Virtual Size:** ${(data.on_chain.network_metrics.mempool_vsize / 1e6).toFixed(2)} MB
- **Network Congestion:** ${data.on_chain.network_metrics.network_congestion}
- **Whale Activity:** ${data.on_chain.whale_activity.signal} (confidence: ${data.on_chain.whale_activity.confidence}%)
- **Exchange Flows:** ${data.on_chain.exchange_flows.status}

---

## 🚨 Anomaly Detection (${data.anomalies.count} flagged)

${data.anomalies.flags.map(a => `
### ${severityEmoji(a.severity)} ${a.type} — ${a.asset}
- **Signal:** ${a.signal}
- **Confidence:** ${(a.confidence * 100).toFixed(0)}%
- **Details:** ${a.description}
`).join('')}

---

## 🎯 Composite Scores
| Asset | Score | Rating | Factors |
|-------|-------|--------|---------|
${Object.entries(data.composite_scores).map(([k, v]) => `| ${k} | ${v.score} | ${v.rating} | ${v.factors.join('; ')} |`).join('\n')}

---

## ⚠️ Data Quality Issues
${data.research_flags.map(f => '- ' + f).join('\n') || 'None'}

---

## 📝 Research Notes
- **Focus:** Early signals not visible in price data
- **Key Insight:** Extreme fear persistence (25, declining from 28) suggests potential contrarian setup for BTC
- **ETH Weakness:** Underperforming BTC by ~3% — monitor for capitulation
- **HIMS Strength:** Positive divergence in fear environment — relative strength leader
- **Mempool:** Elevated at ~100K txs indicating network activity
- **Data Gaps:** Exchange flows, funding rates, whale signals need API integration

---
*Report generated by Alpha Fund Alternative Data Fetcher v2.0*
`;

const reportPath = path.join(__dirname, '..', 'data', 'alternative', `${date}_report.md`);
fs.writeFileSync(reportPath, report);
console.log('Report saved:', reportPath);
