/**
 * Autonomous Business Operation System — Build Executor
 * Takes validated opportunities and builds the MVP artifact.
 */

const fs = require('fs');
const path = require('path');

const CONFIG = require('../config.json');
const LOG_FILE = path.join(CONFIG.workspace, CONFIG.log_file);
const BACKLOG_FILE = path.join(CONFIG.workspace, CONFIG.backlog_file);
const REPORTS_DIR = path.join(CONFIG.workspace, CONFIG.reports_dir);

function log(msg) {
  const entry = `[${new Date().toISOString()}] ${msg}\n`;
  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });
  fs.appendFileSync(LOG_FILE, entry);
}

function loadBacklog() {
  if (!fs.existsSync(BACKLOG_FILE)) return [];
  try { return JSON.parse(fs.readFileSync(BACKLOG_FILE, 'utf8')); } catch(e) { return []; }
}

function saveBacklog(backlog) {
  fs.mkdirSync(path.dirname(BACKLOG_FILE), { recursive: true });
  fs.writeFileSync(BACKLOG_FILE, JSON.stringify(backlog, null, 2));
}

function buildNewsletter(opp) {
  const date = new Date().toISOString().slice(0, 10);
  const reportPath = path.join(REPORTS_DIR, `newsletter_${date}.md`);
  const content = `# ${opp.name} — ${date}

## Market Regime
Scanning contrarian signals across BTC, ETH, MSTR, HIMS.

## Today's Signals
- BTC: monitoring extreme fear persistence
- ETH: monitoring funding divergence
- MIMS: relative strength watch

## Risk Note
Paper trading only. 30-day track record required before real capital.

---
*Generated by Project Claw Core — Autonomous Business Operation System*
`;
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, content);
  return { success: true, artifact: reportPath, type: 'newsletter' };
}

function buildReport(opp) {
  const date = new Date().toISOString().slice(0, 10);
  const reportPath = path.join(REPORTS_DIR, `${opp.id}_${date}.md`);
  const content = `# ${opp.name} — Research Report

**Date:** ${date}  
**Category:** ${opp.category}  
**Revenue Model:** ${opp.revenue_model}

## Opportunity
${opp.description}

## Score
${opp.score}/10

## Evidence
${opp.evidence.slice(-1)[0] ? JSON.stringify(opp.evidence.slice(-1)[0].findings, null, 2) : 'Pending research'}

## Next Steps
1. Build landing page
2. Set up payment
3. Launch distribution

---
*Generated by Project Claw Core — Autonomous Business Operation System*
`;
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, content);
  return { success: true, artifact: reportPath, type: 'report' };
}

async function buildOpportunity(id) {
  const backlog = loadBacklog();
  const opp = backlog.find(b => b.id === id);
  if (!opp) return { success: false, error: 'Opportunity not found' };
  if (!opp.validated) return { success: false, error: 'Opportunity not yet validated' };

  log(`Building opportunity: ${id}`);

  let result;
  switch (opp.category) {
    case 'trading_signals':
    case 'content':
      result = buildNewsletter(opp);
      break;
    default:
      result = buildReport(opp);
  }

  if (result.success) {
    opp.status = 'built';
    opp.artifacts = opp.artifacts || [];
    opp.artifacts.push({ path: result.artifact, type: result.type, created_at: new Date().toISOString() });
    opp.tasks.push({ name: 'build_mvp', status: 'done', result });
  }

  saveBacklog(backlog);
  return { success: true, opportunity: opp, result };
}

async function buildTop() {
  const backlog = loadBacklog();
  const validated = backlog.filter(b => b.validated && b.status !== 'built').sort((a, b) => b.score - a.score);
  const results = [];
  for (const opp of validated.slice(0, 2)) {
    results.push(await buildOpportunity(opp.id));
  }
  return results;
}

module.exports = { buildOpportunity, buildTop };

if (require.main === module) {
  buildTop().then(r => console.log(JSON.stringify(r, null, 2))).catch(e => console.error(e));
}
