// Auto-Reporting System - Daily summaries via email
const { execSync } = require('child_process');
const fs = require('fs');
const path = require('path');

class AutoReporting {
  constructor() {
    this.recipient = 'quentin.fabre05arme@gmail.com';
    this.reportsDir = 'C:\\Users\\quent\\.openclaw\\workspace\\reports';
    this.ensureReportsDir();
  }

  ensureReportsDir() {
    if (!fs.existsSync(this.reportsDir)) {
      fs.mkdirSync(this.reportsDir, { recursive: true });
    }
  }

  async generateDailyReport() {
    console.log('📊 Generating daily report...');
    
    // 1. Market data
    const marketData = await this.getMarketData();
    
    // 2. Calendar events
    const calendarEvents = await this.getCalendarEvents();
    
    // 3. Weather
    const weather = await this.getWeather();
    
    // 4. System status
    const systemStatus = await this.getSystemStatus();
    
    // 5. Research findings
    const research = await this.getResearchSummary();
    
    // Compile report
    const report = this.compileReport({
      marketData,
      calendarEvents,
      weather,
      systemStatus,
      research
    });
    
    // Save locally
    const reportPath = path.join(this.reportsDir, `daily_report_${new Date().toISOString().split('T')[0]}.md`);
    fs.writeFileSync(reportPath, report);
    
    // Send via Gmail
    await this.sendReport(report);
    
    return { success: true, reportPath };
  }

  async getMarketData() {
    try {
      const output = execSync('node mission_control/market_data_service.js --json', {
        cwd: 'C:\\Users\\quent\\.openclaw\\workspace',
        encoding: 'utf8',
        timeout: 30000
      });
      return JSON.parse(output);
    } catch (e) {
      return { assets: {} };
    }
  }

  async getCalendarEvents() {
    try {
      const cmd = 'oo connector run cal.list_schedules --days 1';
      const output = execSync(cmd, { encoding: 'utf8', timeout: 15000 });
      return JSON.parse(output);
    } catch (e) {
      return { events: [] };
    }
  }

  async getWeather() {
    try {
      const cmd = 'oo connector run wttr.in --location "Aix-en-Provence" --format json';
      const output = execSync(cmd, { encoding: 'utf8', timeout: 10000 });
      return JSON.parse(output);
    } catch (e) {
      return { current: { temp: 25, condition: 'Sunny' } };
    }
  }

  async getSystemStatus() {
    try {
      const mem = execSync('wmic OS get FreePhysicalMemory,TotalVisibleMemorySize /value', { encoding: 'utf8' });
      const lines = mem.split('\n');
      let total = 0, free = 0;
      for (const line of lines) {
        if (line.includes('TotalVisibleMemorySize')) total = parseInt(line.split('=')[1]);
        if (line.includes('FreePhysicalMemory')) free = parseInt(line.split('=')[1]);
      }
      
      return {
        memory: { total, free, percentUsed: Math.round((1 - free/total) * 100) },
        uptime: '6+ hours'
      };
    } catch (e) {
      return { memory: { percentUsed: 0 }, uptime: 'unknown' };
    }
  }

  async getResearchSummary() {
    try {
      // Check recent research files
      const researchDir = path.join(this.reportsDir, 'research');
      if (fs.existsSync(researchDir)) {
        const files = fs.readdirSync(researchDir).filter(f => f.endsWith('.md'));
        return { recentPapers: files.length };
      }
      return { recentPapers: 0 };
    } catch (e) {
      return { recentPapers: 0 };
    }
  }

  compileReport(data) {
    const date = new Date().toLocaleDateString('fr-FR', { 
      weekday: 'long', 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    });
    
    const btc = data.marketData.assets?.BTC || {};
    const eth = data.marketData.assets?.ETH || {};
    
    return `
# 📊 Daily Intelligence Report - ${date}

## 💰 Market Summary
- **Bitcoin (BTC)**: $${btc.price?.toLocaleString() || 'N/A'} (${btc.change_24h > 0 ? '+' : ''}${btc.change_24h?.toFixed(2) || 'N/A'}%)
- **Ethereum (ETH)**: $${eth.price?.toLocaleString() || 'N/A'} (${eth.change_24h > 0 ? '+' : ''}${eth.change_24h?.toFixed(2) || 'N/A'}%)

## 📅 Today's Events
${data.calendarEvents.events?.map(e => `- ${e.title} at ${e.start}`).join('\n') || 'No events scheduled'}

## 🌤️ Weather
- **Temperature**: ${data.weather.current?.temp || 'N/A'}°C
- **Condition**: ${data.weather.current?.condition || 'N/A'}

## 💻 System Status
- **Memory Usage**: ${data.systemStatus.memory.percentUsed}%
- **Uptime**: ${data.systemStatus.uptime}

## 🔬 Research
- **Recent Papers**: ${data.research.recentPapers}

---
*Generated by OpenClaw + OOMOL | ${new Date().toLocaleTimeString('fr-FR')}*
`;
  }

  async sendReport(report) {
    try {
      const subject = `📊 Daily Intelligence Report - ${new Date().toLocaleDateString('fr-FR')}`;
      const body = report.replace(/"/g, '\\"').substring(0, 2000); // Gmail limit
      
      const cmd = `oo connector run gmail.send_email --to "${this.recipient}" --subject "${subject}" --body "${body}"`;
      
      execSync(cmd, { encoding: 'utf8', timeout: 30000 });
      console.log('📧 Report sent via Gmail');
    } catch (e) {
      console.error('Failed to send report:', e.message);
    }
  }
}

if (require.main === module) {
  new AutoReporting().generateDailyReport().catch(console.error);
}

module.exports = AutoReporting;
