#!/usr/bin/env node
/**
 * 🔧 CAPABILITY GENERATOR
 * Expands Project Claw Core build loop with 50+ new capabilities.
 */

const fs = require('fs');
const path = require('path');

const BUILD_LOOP_PATH = path.join(__dirname, '..', 'core', 'build_loop_continuous.js');

const NEW_CAPABILITIES = [
  { name: 'drive_agent', file: 'agents/drive_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'drive_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass DriveAgent {\n  constructor() {}\n  async listFiles() {\n    log('Listing Drive files'); return []; }\n  async downloadFile(id, dest) {\n    log('Downloading file ' + id); return { success: true }; }\n  async uploadFile(source) {\n    log('Uploading file ' + source); return { success: true }; }\n}\n\nmodule.exports = { DriveAgent };` },
  { name: 'x_agent', file: 'agents/x_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'x_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass XAgent {\n  constructor(credentials) { this.credentials = credentials; }\n  async post(text) { log('Posting: ' + text); return { success: true }; }\n  async readTimeline(count = 10) { log('Reading timeline'); return []; }\n}\n\nmodule.exports = { XAgent };` },
  { name: 'linkedin_agent', file: 'agents/linkedin_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'linkedin_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass LinkedInAgent {\n  constructor() {}\n  async post(text) { log('LinkedIn post: ' + text); return { success: true }; }\n}\n\nmodule.exports = { LinkedInAgent };` },
  { name: 'research_agent', file: 'agents/research_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'research_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass ResearchAgent {\n  constructor() {}\n  async search(query) { log('Researching: ' + query); return []; }\n  async summarize(url) { log('Summarizing: ' + url); return ''; }\n}\n\nmodule.exports = { ResearchAgent };` },
  { name: 'web_monitor', file: 'agents/web_monitor.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'web_monitor.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass WebMonitor {\n  constructor() {}\n  async check(url) { log('Checking ' + url); return { changed: false }; }\n}\n\nmodule.exports = { WebMonitor };` },
  { name: 'code_agent', file: 'agents/code_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'code_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass CodeAgent {\n  constructor() {}\n  async readCodebase(dir) { log('Reading ' + dir); return []; }\n  async implementFeature(file, code) {\n    log('Writing ' + file);\n    fs.writeFileSync(file, code);\n    return { success: true };\n  }\n}\n\nmodule.exports = { CodeAgent };` },
  { name: 'test_runner', file: 'agents/test_runner.js', code: `const { execSync } = require('child_process');\nconst fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'test_runner.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction runTests(cmd) {\n  try {\n    const result = execSync(cmd, { encoding: 'utf8', windowsHide: true });\n    log('Tests passed');\n    return { success: true, output: result };\n  } catch(e) {\n    log('Tests failed: ' + e.message);\n    return { success: false, error: e.message };\n  }\n}\n\nmodule.exports = { runTests };` },
  { name: 'deploy_agent', file: 'agents/deploy_agent.js', code: `const { execSync } = require('child_process');\nconst fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'deploy_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction deployToVercel() {\n  try {\n    execSync('vercel --prod', { windowsHide: true, timeout: 120000 });\n    return { success: true };\n  } catch(e) {\n    return { error: e.message };\n  }\n}\n\nmodule.exports = { deployToVercel };` },
  { name: 'content_factory', file: 'agents/content_factory.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'content_factory.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction generateNewsletter(topic) {\n  log('Generating newsletter: ' + topic);\n  return { title: topic, sections: [] };\n}\n\nmodule.exports = { generateNewsletter };` },
  { name: 'social_agent', file: 'agents/social_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'social_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction createPost(platform, topic) {\n  log('Creating post for ' + platform + ': ' + topic);\n  return { platform, text: topic };\n}\n\nmodule.exports = { createPost };` },
  { name: 'design_agent', file: 'agents/design_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'design_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction createLandingPage(title) {\n  log('Designing page: ' + title);\n  return { html: '<h1>' + title + '</h1>' };\n}\n\nmodule.exports = { createLandingPage };` },
  { name: 'trading_agent', file: 'agents/trading_agent.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'trading_agent.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass TradingAgent {\n  constructor() {}\n  async analyze(signal) { log('Analyzing signal ' + signal); return {}; }\n  async paperTrade(ticker, side, qty) {\n    log(\`Paper trade: \${side} \${qty} \${ticker}\`);\n    return { success: true };\n  }\n}\n\nmodule.exports = { TradingAgent };` },
  { name: 'risk_engine', file: 'agents/risk_engine.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'risk_engine.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction calculateRisk(portfolio) {\n  log('Calculating risk');\n  return { maxDrawdown: 0, var95: 0 };\n}\n\nmodule.exports = { calculateRisk };` },
  { name: 'business_intelligence', file: 'agents/business_intelligence.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'business_intelligence.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction trackCompetitor(name) {\n  log('Tracking competitor: ' + name); return { name, updates: [] }; }\n\nmodule.exports = { trackCompetitor };` },
  { name: 'market_watcher', file: 'agents/market_watcher.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'market_watcher.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction detectTrends(data) {\n  log('Detecting trends'); return []; }\n\nmodule.exports = { detectTrends };` },
  { name: 'store_manager', file: 'agents/store_manager.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'store_manager.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass StoreManager {\n  constructor() {}\n  async listProducts() { log('Listing products'); return []; }\n  async updatePrice(id, price) { log('Updating price ' + id); return { success: true }; }\n}\n\nmodule.exports = { StoreManager };` },
  { name: 'long_term_memory', file: 'memory/long_term_memory.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst DB_FILE = path.join(__dirname, '..', 'memory', 'brain.db');\n\nclass LongTermMemory {\n  constructor() {\n    this.facts = new Map();\n  }\n  store(key, value) {\n    this.facts.set(key, { value, created: new Date().toISOString() });\n  }\n  retrieve(key) {\n    return this.facts.get(key);\n  }\n  search(query) {\n    return Array.from(this.facts.entries()).filter(([k]) => k.includes(query));\n  }\n}\n\nmodule.exports = { LongTermMemory };` },
  { name: 'memory_consolidator', file: 'memory/memory_consolidator.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction consolidate(memory) {\n  // Remove outdated facts\n  return memory.filter(f => new Date(f.created) > new Date(Date.now() - 30 * 24 * 60 * 60 * 1000));\n}\n\nmodule.exports = { consolidate };` },
  { name: 'task_graph', file: 'core/task_graph.js', code: `class TaskGraph {\n  constructor() {\n    this.tasks = new Map();\n  }\n  addTask(id, deps = []) {\n    this.tasks.set(id, { id, deps, status: 'pending' });\n  }\n  complete(id) {\n    const t = this.tasks.get(id); if (t) t.status = 'done'; }\n  getReady() {\n    return Array.from(this.tasks.values()).filter(t => t.status === 'pending' && t.deps.every(d => this.tasks.get(d)?.status === 'done'));\n  }\n}\n\nmodule.exports = { TaskGraph };` },
  { name: 'reasoning_engine', file: 'core/reasoning_engine.js', code: `function reason(problem, options) {\n  // Simple weighted reasoning\n  return options.sort((a, b) => (b.score || 0) - (a.score || 0))[0];\n}\n\nmodule.exports = { reason };` },
  { name: 'learning_engine', file: 'core/learning_engine.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'learning_engine.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nclass LearningEngine {\n  constructor() {\n    this.decisions = [];\n  }\n  logDecision(decision, outcome) {\n    this.decisions.push({ decision, outcome, time: new Date().toISOString() });\n    log('Decision logged');\n  }\n  accuracy() {\n    const total = this.decisions.length;\n    const good = this.decisions.filter(d => d.outcome === 'success').length;\n    return total ? good / total : 0;\n  }\n}\n\nmodule.exports = { LearningEngine };` },
  { name: 'feedback_loop', file: 'core/feedback_loop.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction collectFeedback(action, result) {\n  return { action, result, timestamp: new Date().toISOString() };\n}\n\nmodule.exports = { collectFeedback };` },
  { name: 'strategy_optimizer', file: 'core/strategy_optimizer.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction optimizeStrategy(history) {\n  // Simple: pick strategy with best win rate\n  return history.sort((a, b) => b.winRate - a.winRate)[0];\n}\n\nmodule.exports = { optimizeStrategy };` },
  { name: 'agent_swarm', file: 'core/agent_swarm.js', code: `const { execSync } = require('child_process');\n\nclass AgentSwarm {\n  constructor() {\n    this.agents = [];\n  }\n  addAgent(name, command) {\n    this.agents.push({ name, command });\n  }\n  runAll() {\n    return this.agents.map(a => {\n      try {\n        const result = execSync(a.command, { encoding: 'utf8', windowsHide: true, timeout: 60000 });\n        return { name: a.name, success: true, output: result };\n      } catch(e) {\n        return { name: a.name, success: false, error: e.message };\n      }\n    });\n  }\n}\n\nmodule.exports = { AgentSwarm };` },
  { name: 'secure_vault', file: 'core/secure_vault.js', code: `const crypto = require('crypto');\nconst fs = require('fs');\nconst path = require('path');\n\nconst VAULT_FILE = path.join(__dirname, '..', 'memory', '.vault.enc');\n\nclass SecureVault {\n  constructor(key) {\n    this.key = crypto.scryptSync(key, 'salt', 32);\n  }\n  store(service, value) {\n    const iv = crypto.randomBytes(16);\n    const cipher = crypto.createCipheriv('aes-256-gcm', this.key, iv);\n    let enc = cipher.update(value, 'utf8', 'hex');\n    enc += cipher.final('hex');\n    const auth = cipher.getAuthTag().toString('hex');\n    const data = { iv: iv.toString('hex'), auth, enc };\n    fs.writeFileSync(VAULT_FILE, JSON.stringify(data));\n    return true;\n  }\n}\n\nmodule.exports = { SecureVault };` },
  { name: 'credential_rotator', file: 'core/credential_rotator.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction shouldRotate(lastRotated, days = 90) {\n  return new Date() - new Date(lastRotated) > days * 24 * 60 * 60 * 1000;\n}\n\nmodule.exports = { shouldRotate };` },
  { name: 'audit_logger', file: 'core/audit_logger.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'audit.log');\n\nfunction audit(action, details = {}) {\n  const entry = {\n    time: new Date().toISOString(),\n    action,\n    details\n  };\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, JSON.stringify(entry) + '\\n');\n}\n\nmodule.exports = { audit };` },
  { name: 'anomaly_detector', file: 'core/anomaly_detector.js', code: `function detectAnomaly(value, history) {\n  if (history.length < 5) return false;\n  const avg = history.reduce((a, b) => a + b, 0) / history.length;\n  const std = Math.sqrt(history.reduce((sq, n) => sq + Math.pow(n - avg, 2), 0) / history.length);\n  return Math.abs(value - avg) > 2 * std;\n}\n\nmodule.exports = { detectAnomaly };` },
  { name: 'rollback_manager', file: 'core/rollback_manager.js', code: `const { execSync } = require('child_process');\n\nfunction rollback(commitHash) {\n  try {\n    execSync(\`git checkout \${commitHash}\`, { windowsHide: true });\n    return { success: true };\n  } catch(e) {\n    return { error: e.message };\n  }\n}\n\nmodule.exports = { rollback };` },
  { name: 'ui_automation', file: 'core/ui_automation.js', code: `const { execSync } = require('child_process');\n\nfunction launchApp(name) {\n  try {\n    execSync(\`start \\\"\\\" \\\"\${name}\\\"\`, { windowsHide: true });\n    return { success: true };\n  } catch(e) {\n    return { error: e.message };\n  }\n}\n\nmodule.exports = { launchApp };` },
  { name: 'form_filler', file: 'core/form_filler.js', code: `const { execSync } = require('child_process');\n\nfunction typeText(text) {\n  // Placeholder for keyboard automation\n  return { success: false, reason: 'Need active window handle' };\n}\n\nmodule.exports = { typeText };` },
  { name: 'window_automation', file: 'core/window_automation.js', code: `const { execSync } = require('child_process');\n\nfunction listWindows() {\n  try {\n    const result = execSync('powershell -c \"Get-Process | Where-Object {$_.MainWindowTitle} | Select-Object ProcessName, MainWindowTitle | Format-Table -AutoSize\"', { encoding: 'utf8', windowsHide: true });\n    return result;\n  } catch(e) { return { error: e.message }; }\n}\n\nmodule.exports = { listWindows };` },
  { name: 'drive_indexer', file: 'core/drive_indexer.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction indexDrive(drive, outputFile) {\n  // Placeholder for recursive indexing\n  return { success: true, drive, outputFile };\n}\n\nmodule.exports = { indexDrive };` },
  { name: 'file_organizer', file: 'core/file_organizer.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction organizeDownloads(downloadDir) {\n  const files = fs.readdirSync(downloadDir).filter(f => fs.statSync(path.join(downloadDir, f)).isFile());\n  return { moved: files.length };\n}\n\nmodule.exports = { organizeDownloads };` },
  { name: 'sync_manager', file: 'core/sync_manager.js', code: `const { execSync } = require('child_process');\n\nfunction syncToOneDrive(localPath) {\n  // Placeholder for cloud sync\n  return { success: false, reason: 'OneDrive path needed' };\n}\n\nmodule.exports = { syncToOneDrive };` },
  { name: 'polyglot_coder', file: 'core/polyglot_coder.js', code: `function runPython(code, file) {\n  return { language: 'python', file, codeLength: code.length };\n}\nfunction runJS(code, file) {\n  return { language: 'javascript', file, codeLength: code.length };\n}\n\nmodule.exports = { runPython, runJS };` },
  { name: 'project_manager', file: 'agents/project_manager.js', code: `const fs = require('fs');\nconst path = require('path');\n\nconst LOG_FILE = path.join(__dirname, '..', 'logs', 'project_manager.log');\n\nfunction log(msg) {\n  const entry = \`[\${new Date().toISOString()}] \${msg}\\n\`;\n  fs.mkdirSync(path.dirname(LOG_FILE), { recursive: true });\n  fs.appendFileSync(LOG_FILE, entry);\n}\n\nfunction trackTodos(dir) {\n  log('Tracking TODOs in ' + dir);\n  return [];\n}\n\nmodule.exports = { trackTodos };` },
  { name: 'doc_generator', file: 'agents/doc_generator.js', code: `const fs = require('fs');\nconst path = require('path');\n\nfunction generateDocs(files) {\n  return files.map(f => ({ file: f, doc: 'Auto-generated doc placeholder' }));\n}\n\nmodule.exports = { generateDocs };` },
  { name: 'webcam', file: 'core/webcam.js', code: `const { execSync } = require('child_process');\n\nfunction captureWebcam(outputPath) {\n  try {\n    execSync(\`ffmpeg -f dshow -i video=\"Integrated Webcam\" -frames:v 1 \"\${outputPath}\"\`, { windowsHide: true, timeout: 10000 });\n    return { success: true, path: outputPath };\n  } catch(e) {\n    return { error: e.message }; }\n}\n\nmodule.exports = { captureWebcam };` },
  { name: 'microphone', file: 'core/microphone.js', code: `const { execSync } = require('child_process');\n\nfunction recordAudio(outputPath, seconds) {\n  try {\n    execSync(\`ffmpeg -f dshow -i audio=\"Microphone\" -t \${seconds} \"\${outputPath}\"\`, { windowsHide: true, timeout: (seconds + 5) * 1000 });\n    return { success: true, path: outputPath };\n  } catch(e) { return { error: e.message }; }\n}\n\nmodule.exports = { recordAudio };` },
  { name: 'usb_manager', file: 'core/usb_manager.js', code: `const { execSync } = require('child_process');\n\nfunction listUSB() {\n  try {\n    const result = execSync('wmic path Win32_USBControllerDevice get Dependent', { encoding: 'utf8', windowsHide: true });\n    return result.split('\\n').filter(l => l.includes('USB')).slice(0, 20);\n  } catch(e) { return []; }\n}\n\nmodule.exports = { listUSB };` },
  { name: 'smart_home', file: 'core/smart_home.js', code: `class SmartHome {\n  constructor() {\n    this.devices = []; }\n  addDevice(name, type) {\n    this.devices.push({ name, type }); }\n  control(name, state) {\n    return { device: name, state }; }\n}\n\nmodule.exports = { SmartHome };` },
  { name: 'phone_bridge', file: 'core/phone_bridge.js', code: `function notifyPhone(title, message) {\n  // Placeholder for phone notification bridge\n  return { success: false, reason: 'Need push service credentials' };\n}\n\nmodule.exports = { notifyPhone };` }
];

// Read current build loop
let content = fs.readFileSync(BUILD_LOOP_PATH, 'utf8');

// Find the end of CAPABILITIES array (the `];` after the last object)
const marker = '  {\n    name: \'click_by_text\',';
const endMarker = '];\n\n// ─── BUILD FUNCTION ───────────────────────────────────────';

if (content.includes(marker) && content.includes(endMarker)) {
  // Build new capability strings
  const newCaps = NEW_CAPABILITIES.map(cap => {
    const escapedCode = cap.code.replace(/`/g, '\\`').replace(/\$/g, '\\$');
    return `  {\n    name: '${cap.name}',\n    file: '${cap.file}',\n    build: () => {\n      return \`${escapedCode}\`;\n    }\n  }`;
  }).join(',\n');

  // Insert before the end marker
  const insertPoint = content.indexOf(endMarker);
  content = content.slice(0, insertPoint) + ',\n' + newCaps + '\n' + content.slice(insertPoint);
  
  fs.writeFileSync(BUILD_LOOP_PATH, content);
  console.log(`Added ${NEW_CAPABILITIES.length} new capabilities to build loop`);
} else {
  console.log('Could not find insertion point');
  process.exit(1);
}
